### ISSUE TITLE
Doesn't follow & Retweet old tweet

### ISSUE THREAD

**Issue by Trytotry2** [fmaury/Twitbot_Concours#1]
Hello,
So, to begin, thank's for the bot, it's pretty easy to use and seems to well work.

I'm using the bot since few days and I have seen that the bot doesn't follow the Twitter Account in the tweet from time to time.
When I check some Retweet the bot have made, sometimes, there is an account which is not followed, and each time is an account that's write in the tweet, and not the sender himself.

A saw another issue in the age of the tweet. I saw my bot retweet some tweet that have been launched few months ago (like 10 months for the older I saw), which is useless to retweet a giveaway that have been ended a long time ago... It's even dangerous because is the organizer check the account and see a recent retweet for an old giveaway, he can have some doubts on who is behind the account, a man or a bot.

In another case : 
- Is there a way to reduce the 1000 retweet goal to reduce it to 500 ? (Or maybe add a variable in the config file to let the user chose it ?)

Thank's for your help.

**Comment by fmaury** [comment]
Hi,

I liked your idea about a config file so I added one with some stuff you can modify including the maximum date of the tweet.

I found a bug on the follow part, that happened because sometimes the last account name mentionned in the tweet had a dot at the end because it was the end of the sentence.

Thanks for the report and let me know if you find something else :)

**Comment by Trytotry2** [comment]
Hi, I just download the new version of your bot. Thank's for the config file, it will be useful.

Is there a way to select more than one language ? The config file doesn't explain if we can or not. I'm using 'fr' but would like to use 'en' too.

Same question for the trends.

For the others lines, just thank you ^^
